name: Generate Development Repository
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
      - '*-dev'

# ${{ github.event.repository.name }}
# ${{ steps.release.outputs.pre-release }}

jobs:
  repo-gen:
    if: github.repository == 'anxdpanic/plugin.video.youtube' || github.event_name == 'workflow_dispatch'
    name: Generate development repository and upload to mirrors
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Release Status
        id: release
        run: |
          version=${GITHUB_REF/refs\/tags\//}
          if [[ $version == *[-+]@(alpha|beta|dev)*([.0-9a-z]) ]] ;
          then
            echo "pre-release=true" >> $GITHUB_OUTPUT
          else
            echo "pre-release=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml

      - name: Checkout Official Add-on
        uses: actions/checkout@v4
        with:
          repository: "anxdpanic/plugin.video.youtube"
          path: ./official/plugin.video.youtube
          ref: "master"

      - name: Checkout Unofficial Add-on
        uses: actions/checkout@v4
        with:
          repository: "anxdpanic/plugin.video.youtube"
          path: ./unofficial/plugin.video.youtube
          ref: "nexus-unofficial"

      - name: Checkout Add-on
        uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}

      - name: Make Repository Add-on Directories
        run: |
          mkdir ./official/repository.yt.testing_official
          mkdir ./unofficial/repository.yt.testing_unofficial

      - name: Download Official Repository Add-on Files from FTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          user: ${{ secrets.FTP_USERNAME }}
          pass: ${{ secrets.FTP_PASSWORD }}
          onlyNewer: false
          settings: 'sftp:auto-confirm=yes'
          localDir: './official/repository.yt.testing_official'
          remoteDir: '/root/anxdpanic/kodi/youtube/repository.yt.testing_official'
          reverse: true
          options: '--verbose'

      - name: Download Unofficial Repository Add-on Files from FTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          user: ${{ secrets.FTP_USERNAME }}
          pass: ${{ secrets.FTP_PASSWORD }}
          onlyNewer: false
          settings: 'sftp:auto-confirm=yes'
          localDir: './unofficial/repository.yt.testing_unofficial'
          remoteDir: '/root/anxdpanic/kodi/youtube/repository.yt.testing_unofficial'
          reverse: true
          options: '--verbose'

      # cp  ./official/plugin.video.youtube/.scripts/* .
      - name: Copy Generator Script
        run: |
          cp  ${{ github.event.repository.name }}/.scripts/.prepare_repository.py .
          cp  ${{ github.event.repository.name }}/.scripts/.config.json .

      - name: Generate Repository
        run: |
          python .prepare_repository.py

      - name: List Generated Repository for Debug
        run: |
          ls -la ./repository/official
          ls -la ./repository/official/zips
          ls -la ./repository/unofficial          
          ls -la ./repository/unofficial/zips
