# Based on https://github.com/im85288/service.upnext/blob/master/.github/workflows/release.yml
name: Generate Development Repository
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
      - '*-dev'

# ${{ github.event.repository.name }}
jobs:
  repo-gen:
    # if: github.repository == 'anxdpanic/plugin.video.youtube' || github.event_name == 'workflow_dispatch'
    name: Generate development repository and upload to mirrors
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout Official Add-on
        uses: actions/checkout@v4
        with:
          repository: "anxdpanic/plugin.video.youtube"
          path: ./official/plugin.video.youtube
          ref: "master"

      - name: Checkout Unofficial Add-on
        uses: actions/checkout@v4
        with:
          repository: "anxdpanic/plugin.video.youtube"
          path: ./unofficial/plugin.video.youtube
          ref: "nexus-unofficial"

      - name: Checkout Add-on
        uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}

      - name: Install dependencies
        run: |
          sudo apt-get update

      # cp  ./official/plugin.video.youtube/.scripts/* .
      - name: Copy Generator Script
        id: copy-gen-script
        run: |
          cp  ${{ github.event.repository.name }}/.scripts/.prepare_repository.py .
          cp  ${{ github.event.repository.name }}/.scripts/.config.json .

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate Repository
        run: |
          python .prepare_repository.py
          ls -la ./official/plugin.video.youtube
          ls -la ./unofficial/plugin.video.youtube
